### ISSUE TITLE
palette issues (last version)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [alaahadid/My-Nes#2]
Something strange happens with new MyNES palette generator:
![test](https://user-images.githubusercontent.com/13199529/116910520-6a8d3e00-ac4e-11eb-959a-c926e2f16142.png)
I have real UA6538 PPU capture (it similar to PAL NES RP2C07 PPU regarding palette):
![pal_capture_UA6538](https://user-images.githubusercontent.com/13199529/116910704-a45e4480-ac4e-11eb-9545-90002e8c3db8.png)
test rom:
[_nes_palette_viewer.zip](https://github.com/alaahadid/My-Nes/files/6416560/_nes_palette_viewer.zip)

**Comment by alaahadid** [comment]
Hi,
The new version of My Nes does not use palette generator anymore, it decode colors directly from nes register and palette bank values. This is implemented in version 7.9.7793.23986 and still in testing mode. The older version  [7.9.7791.3517](https://github.com/alaahadid/My-Nes/releases/tag/v7.9.7791.3517) can be used since there is no change between the 2 versions for the exception of palette.
Sill working on color decoding and all bugs should be fixed soon, I was so excited that why i made it in  a release today :)

**Comment by alaahadid** [comment]
With the [latest release](https://github.com/alaahadid/My-Nes/releases/tag/v7.9.7795.37773), this how My Nes show colors:
<img width="949" alt="Capture 1" src="https://user-images.githubusercontent.com/5833268/117196820-47e25d00-ade7-11eb-928c-d67d51669b90.PNG">
<img width="948" alt="Capture 2" src="https://user-images.githubusercontent.com/5833268/117196824-487af380-ade7-11eb-95ed-217ff2c85990.PNG">
The colors are decoded in runtime, no need for palette. I documented this [here](https://github.com/alaahadid/Nes-Docs/blob/main/Color%20Decoding%20In%20PPU.txt).
The first entry should be light blue, but after implementing the decoding, it is displayed as a dark blue. I think more modification is needed but in the emu core, in the video renderer i think. Maybe this will be done in later version of My Nes. If the new update is not preferred, My Nes still can be used with [version 7.9.7791.3517](https://github.com/alaahadid/My-Nes/releases/tag/v7.9.7791.3517) since in that version My Nes uses palette indexes instead of real time color decoding.
